<a href="https://colab.research.google.com/github/roshain-wijewardene/Reinforcement-learning/blob/main/reinforcement-learning-project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# CS 3120 - Machine Learning and Neural Computing

**Reinforcement Learning - Part 03**

*   Name : D. R. R. Wijewardene
*   Index Number : S14245
*   Faculty : Science (Bioinformatics)

# **Exercise**

In [ ]:
import numpy as np

# States and Actions of the maze

**State = Row Index**

*   (0,0) = 0 **START**
*   (0,1) = 1
*   (0,2) = 2
*   (0,3) = 3
*   (-1,-1) = 4
*   (-1,2) = 5
*   (-1,3) = 6
*   (1,1) = 7
*   (1,2) = 8
*   (2,-1) = 9
*   (2,1) = 10
*   (2,2) = 11
*   (3,2) = 12
*   (3,3) = 13
*   (3,1) = 14 **END (Goal)**




In [ ]:
rows = 15

**Action = Column Index**

*   Up = 0
*   Down = 1
*   Left = 2
*   Right = 3

In [ ]:
columns = 4

# State Transitions

State vs Action -> Next State

In [ ]:
path = np.matrix([[1,-1,-1,-1],[2,0,-1,7],[3,1,-1,8],[-1,2,6,-1],[5,-1,-1,9],[6,4,-1,-1],[-1,5,-1,3],[8,-1,1,10],[-1,7,2,11],[10,-1,4,-1],[11,9,7,14],[-1,10,8,12],[13,-1,11,-1],[-1,12,-1,-1],[-1,-1,10,-1]])
path

matrix([[ 1, -1, -1, -1],
        [ 2,  0, -1,  7],
        [ 3,  1, -1,  8],
        [-1,  2,  6, -1],
        [ 5, -1, -1,  9],
        [ 6,  4, -1, -1],
        [-1,  5, -1,  3],
        [ 8, -1,  1, 10],
        [-1,  7,  2, 11],
        [10, -1,  4, -1],
        [11,  9,  7, 14],
        [-1, 10,  8, 12],
        [13, -1, 11, -1],
        [-1, 12, -1, -1],
        [-1, -1, 10, -1]])

# Reward

**Reward for reaching each state**

In [ ]:
State_reward = np.matrix([[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[100]])
State_reward

matrix([[  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [100]])

# Q table

**Initial Q table**

In [ ]:
Q = np.matrix(np.zeros([rows,columns]))
Q

matrix([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

# Exploration
*when sequences are given*

**Episodes**

1.   Start = (0, 0) -> **0**
> Actions: UP, RIGHT, RIGHT, RIGHT
2.   Start = (0, 2) -> **2**
> Actions: DOWN, RIGHT, UP, RIGHT, DOWN, RIGHT
3.   Start = (1, 2) -> **8**
> Actions: DOWN, RIGHT, RIGHT

In [ ]:
# Initial States of each episode

epi_initial = np.array([[0],[2],[8]])
epi_initial

array([[0],
       [2],
       [8]])

In [ ]:
# Path of each episode

epi_path = np.array([[0,3,3,3],[1,3,0,3,1,3],[1,3,3]],dtype=object)
epi_path

array([list([0, 3, 3, 3]), list([1, 3, 0, 3, 1, 3]), list([1, 3, 3])],
      dtype=object)

**Updating the Q table**

In [ ]:
gamma = 0.8   # learning rate

epi = 0       # initial episode

while epi < 3:
  for a in epi_path:
    state_A = epi_initial[epi][0]
    for b in a:
      state_B = path[state_A , b]

      max_index = np.where(Q[state_B,] == np.max(Q[state_B,]))[1]

      if max_index.shape[0] > 1:
        max_index = int(np.random.choice(max_index, size=1))
      else:
        max_index = int(max_index)

      max_value = Q[state_B, max_index]

      reward = State_reward[state_B , 0]

      Q[state_A, b] = reward + gamma * max_value    # Q update rule
      print('Max_value', reward + gamma * max_value)

      if (np.max(Q) > 0):
        print(np.sum(Q / np.max(Q)*100))
      else:
        print(0)

      state_A = state_B

    epi = epi + 1
    print(Q / np.max(Q)*100)

Max_value 0.0
0
Max_value 0.0
0
Max_value 0.0
0
Max_value 100.0
100.0
[[  0.   0.   0.   0.]
 [  0.   0.   0.   0.]
 [  0.   0.   0.   0.]
 [  0.   0.   0.   0.]
 [  0.   0.   0.   0.]
 [  0.   0.   0.   0.]
 [  0.   0.   0.   0.]
 [  0.   0.   0.   0.]
 [  0.   0.   0.   0.]
 [  0.   0.   0.   0.]
 [  0.   0.   0. 100.]
 [  0.   0.   0.   0.]
 [  0.   0.   0.   0.]
 [  0.   0.   0.   0.]
 [  0.   0.   0.   0.]]
Max_value 0.0
100.0
Max_value 0.0
100.0
Max_value 0.0
100.0
Max_value 0.0
100.0
Max_value 80.0
180.0
Max_value 100.0
180.0
[[  0.   0.   0.   0.]
 [  0.   0.   0.   0.]
 [  0.   0.   0.   0.]
 [  0.   0.   0.   0.]
 [  0.   0.   0.   0.]
 [  0.   0.   0.   0.]
 [  0.   0.   0.   0.]
 [  0.   0.   0.   0.]
 [  0.   0.   0.   0.]
 [  0.   0.   0.   0.]
 [  0.   0.   0. 100.]
 [  0.  80.   0.   0.]
 [  0.   0.   0.   0.]
 [  0.   0.   0.   0.]
 [  0.   0.   0.   0.]]
Max_value 0.0
180.0
Max_value 80.0
260.0
Max_value 100.0
260.0
[[  0.   0.   0.   0.]
 [  0.   0.   0.   0.]
 [  0.

**Trained Q-table (after 3 given episodes)**

In [ ]:
print("Q table after 3 given episodes : ")
print(Q/np.max(Q)*100)

Q table after 3 given episodes : 
[[  0.   0.   0.   0.]
 [  0.   0.   0.   0.]
 [  0.   0.   0.   0.]
 [  0.   0.   0.   0.]
 [  0.   0.   0.   0.]
 [  0.   0.   0.   0.]
 [  0.   0.   0.   0.]
 [  0.   0.   0.  80.]
 [  0.   0.   0.   0.]
 [  0.   0.   0.   0.]
 [  0.   0.   0. 100.]
 [  0.  80.   0.   0.]
 [  0.   0.   0.   0.]
 [  0.   0.   0.   0.]
 [  0.   0.   0.   0.]]


# Exploitation

*When*
> Initial state is (0,0) -> index 0

> Goal state  = (3,1) -> 14

In [ ]:
current_state = 0
goal_state = 14

most_efficient_path =[]


while current_state != goal_state:

    next_state_index = np.where(Q[current_state,] == np.max(Q[current_state,]))[1]

    if next_state_index.shape[0] > 1:
        next_state_index = int(np.random.choice(next_state_index, size = 1))
    else:
        next_state_index = int(next_state_index)


    next_state = path[current_state,next_state_index]


    if next_state != -1:
      most_efficient_path.extend([next_state_index])


      current_state = next_state

    else:

      current_state =current_state

print("Indexes of ACTIONS :\nUP \t= 0\nDOWN \t= 1\nLEFT \t= 2\nRIGHT \t= 3")
print("")

print("Goal state = (3,1) -> Index 14")
print("")

print("Trained Episodes :")
print("")

print("Episode 1 : \tStart = (0,0) -> Index 0 ; \tActions: UP, RIGHT, RIGHT, RIGHT\nEpisode 2 : \tStart = (0,2) -> Index 2 ; \tActions: DOWN, RIGHT, UP, RIGHT, DOWN, RIGHT\nEpisode 3 : \tStart = (1,2) -> Index 8 ; \tActions: DOWN, RIGHT, RIGHT")
print("")

print("Exploitation :")
print("")

print("when the Start State is (0,0) -> Index 0 ,")

print("\t\t The Actions to follow the Most Efficient Path towards the Goal State  :\t",most_efficient_path)

Indexes of ACTIONS :
UP 	= 0
DOWN 	= 1
LEFT 	= 2
RIGHT 	= 3

Goal state = (3,1) -> Index 14

Trained Episodes :

Episode 1 : 	Start = (0,0) -> Index 0 ; 	Actions: UP, RIGHT, RIGHT, RIGHT
Episode 2 : 	Start = (0,2) -> Index 2 ; 	Actions: DOWN, RIGHT, UP, RIGHT, DOWN, RIGHT
Episode 3 : 	Start = (1,2) -> Index 8 ; 	Actions: DOWN, RIGHT, RIGHT

Exploitation :

when the Start State is (0,0) -> Index 0 ,
		 The Actions to follow the Most Efficient Path towards the Goal State  :	 [0, 3, 3, 3]
